data<- read.table(file.choose(),stringsAsFactors = FALSE,header = TRUE, sep= ";")
data$Date<- as.Date(data$Date,"%d/%m/%Y") 
d<- which(data$Date == "2007-02-01"| data$Date == "2007-02-02")
udata<- data[d,]
dateTime<-strptime(p,"%Y-%m-%d %H:%M:%S")
par(mfrow=c(2,2))
plot(dateTime,udata$Global_active_power, type = "l", ylab ="Global Active Power", xlab="" )
plot(dateTime,udata$Voltage, type = "l", ylab ="Voltage", xlab="datetime" )
plot(dateTime,udata$Sub_metering_1,xlab="",ylab="Energy sub metering",type="l")
lines(dateTime, udata$Sub_metering_2,col="red")
lines(dateTime, udata$Sub_metering_3,col="blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col= c("black","red","blue"),lwd=2.5,cex=0.2)
plot(dateTime,udata$Global_reactive_power, type = "l", ylab ="Global_reactive_power", xlab="datetime",ylim=c(0.0,0.5) )
dev.copy(png,file="plot4.png",width=480,height=480,units="px")
dev.off()